import { Item } from './types';

export const mockItems: Item[] = [
  {
    id: 'a1b2c3d4e5f6',
    source: 'extension',
    url: 'https://example.com/distributed-systems-2025',
    url_hash: 'hash001',
    title: 'Distributed Systems Patterns for Modern Cloud Applications',
    summary_short: 'クラウドネイティブ時代の分散システム設計パターンを解説',
    summary_long: 'マイクロサービスアーキテクチャにおける分散システム設計パターンを包括的に解説。サーキットブレーカー、サガパターン、イベントソーシングなどの主要パターンについて、実装例とトレードオフを詳述。Kubernetes環境での実践的な適用方法にも言及。',
    tags: ['distributed-systems', 'cloud-native', 'microservices'],
    personal_score: 0.92,
    org_score: 0.75,
    novelty: 0.68,
    base_score: 0.82,
    status: 'active',
    pin: 1,
    r2_path: 'content/2025/01/a1b2c3d4e5f6.txt.gz',
    created_at: '2025-01-15T09:30:00Z',
    processed_at: '2025-01-15T09:30:45Z',
  },
  {
    id: 'b2c3d4e5f6g7',
    source: 'webhook',
    url: 'https://example.com/llm-fine-tuning-guide',
    url_hash: 'hash002',
    title: 'Practical Guide to LLM Fine-Tuning in Production',
    summary_short: 'LLMファインチューニングの実践ガイド。本番環境での注意点を網羅',
    summary_long: 'LLMのファインチューニングを本番環境で行う際のベストプラクティスを解説。データ準備、ハイパーパラメータ調整、評価指標の選定、デプロイメントパイプラインの構築まで、エンドツーエンドの手順を紹介。LoRAやQLoRAなどの効率的な手法にも言及。',
    tags: ['llm', 'fine-tuning', 'machine-learning', 'production'],
    personal_score: 0.88,
    org_score: 0.82,
    novelty: 0.55,
    base_score: 0.76,
    status: 'active',
    pin: 0,
    r2_path: 'content/2025/01/b2c3d4e5f6g7.txt.gz',
    created_at: '2025-01-14T14:20:00Z',
    processed_at: '2025-01-14T14:21:10Z',
  },
  {
    id: 'c3d4e5f6g7h8',
    source: 'manual',
    url: 'https://example.com/team-topologies-review',
    url_hash: 'hash003',
    title: 'Team Topologies: Organizing for Fast Flow - Book Review',
    summary_short: 'Team Topologies書評。組織設計とソフトウェアデリバリーの関係を考察',
    summary_long: 'Team Topologiesの主要概念を要約し、実組織への適用事例を紹介。ストリームアラインドチーム、プラットフォームチーム、イネーブリングチーム、コンプリケイテッドサブシステムチームの4類型について、著者の実体験を交えて解説。',
    tags: ['organization', 'team-topologies', 'engineering-management'],
    personal_score: 0.72,
    org_score: 0.88,
    novelty: 0.42,
    base_score: 0.7,
    status: 'active',
    pin: 0,
    r2_path: 'content/2025/01/c3d4e5f6g7h8.txt.gz',
    created_at: '2025-01-13T11:00:00Z',
    processed_at: '2025-01-13T11:01:30Z',
  },
  {
    id: 'd4e5f6g7h8i9',
    source: 'extension',
    url: 'https://example.com/rust-async-runtime',
    url_hash: 'hash004',
    title: 'Understanding Rust Async Runtime Internals',
    summary_short: 'Rustの非同期ランタイムの内部構造を深掘り',
    summary_long: 'Tokioを中心としたRustの非同期ランタイムの内部実装を解説。Future trait、Waker、タスクスケジューリングの仕組みを図解付きで説明。独自ランタイム実装のチュートリアルも含む。',
    tags: ['rust', 'async', 'systems-programming'],
    personal_score: 0.85,
    org_score: 0.35,
    novelty: 0.72,
    base_score: 0.71,
    status: 'active',
    pin: 0,
    r2_path: 'content/2025/01/d4e5f6g7h8i9.txt.gz',
    created_at: '2025-01-12T16:45:00Z',
    processed_at: '2025-01-12T16:46:20Z',
  },
  {
    id: 'e5f6g7h8i9j0',
    source: 'webhook',
    url: 'https://example.com/platform-engineering-maturity',
    url_hash: 'hash005',
    title: 'Platform Engineering Maturity Model',
    summary_short: 'プラットフォームエンジニアリングの成熟度モデルを提案',
    summary_long: 'プラットフォームエンジニアリングの成熟度を5段階で定義し、各段階での具体的な施策とKPIを提示。内部開発者プラットフォーム(IDP)の構築ロードマップとして活用可能。Backstage、Kratixなどのツール比較も含む。',
    tags: ['platform-engineering', 'developer-experience', 'devops'],
    personal_score: 0.78,
    org_score: 0.91,
    novelty: 0.60,
    base_score: 0.78,
    status: 'active',
    pin: 1,
    r2_path: 'content/2025/01/e5f6g7h8i9j0.txt.gz',
    created_at: '2025-01-11T08:15:00Z',
    processed_at: '2025-01-11T08:16:00Z',
  },
  {
    id: 'f6g7h8i9j0k1',
    source: 'manual',
    url: 'https://example.com/investment-strategy-2025',
    url_hash: 'hash006',
    title: '2025年のテック投資戦略: AIバブルを見極める',
    summary_short: 'AI関連銘柄の投資判断フレームワークを提示',
    summary_long: 'AIバブルの歴史的類似性を分析し、現在のテック投資環境における合理的な判断フレームワークを提案。バリュエーション指標、技術的堀の評価、市場シェア動向の3軸で銘柄スクリーニングする手法を解説。',
    tags: ['investment', 'ai', 'strategy'],
    personal_score: 0.65,
    org_score: 0.20,
    novelty: 0.80,
    base_score: 0.55,
    status: 'active',
    pin: 0,
    r2_path: 'content/2025/01/f6g7h8i9j0k1.txt.gz',
    created_at: '2025-01-10T20:00:00Z',
    processed_at: '2025-01-10T20:01:15Z',
  },
  {
    id: 'g7h8i9j0k1l2',
    source: 'extension',
    url: 'https://example.com/observability-best-practices',
    url_hash: 'hash007',
    title: 'Observability Best Practices for Microservices',
    summary_short: 'マイクロサービスにおけるオブザーバビリティのベストプラクティス',
    summary_long: 'OpenTelemetryを中心としたマイクロサービスのオブザーバビリティ構築手法を解説。構造化ログ、分散トレーシング、メトリクスの三本柱を統合的に実装する方法と、アラート戦略について述べる。',
    tags: ['observability', 'microservices', 'opentelemetry'],
    personal_score: 0.70,
    org_score: 0.65,
    novelty: 0.38,
    base_score: 0.58,
    status: 'muted',
    pin: 0,
    r2_path: 'content/2025/01/g7h8i9j0k1l2.txt.gz',
    created_at: '2025-01-09T12:30:00Z',
    processed_at: '2025-01-09T12:31:45Z',
  },
  {
    id: 'h8i9j0k1l2m3',
    source: 'webhook',
    url: 'https://example.com/wasm-edge-computing',
    url_hash: 'hash008',
    title: 'WebAssembly at the Edge: The Next Computing Paradigm',
    summary_short: 'エッジコンピューティングにおけるWebAssemblyの可能性を探る',
    summary_long: 'Cloudflare Workers、Fastly Compute、VercelなどのエッジランタイムにおけるWebAssemblyの活用事例を比較分析。WASIの進化とコンポーネントモデルがもたらす新しいアプリケーションアーキテクチャについて考察。',
    tags: ['webassembly', 'edge-computing', 'cloudflare'],
    personal_score: 0.82,
    org_score: 0.70,
    novelty: 0.65,
    base_score: 0.75,
    status: 'active',
    pin: 0,
    r2_path: 'content/2025/01/h8i9j0k1l2m3.txt.gz',
    created_at: '2025-01-08T17:00:00Z',
    processed_at: '2025-01-08T17:01:30Z',
  },
  {
    id: 'i9j0k1l2m3n4',
    source: 'manual',
    url: 'https://example.com/database-scaling-patterns',
    url_hash: 'hash009',
    title: 'Database Scaling Patterns: From Single Node to Global Distribution',
    summary_short: 'データベーススケーリングパターンの包括的ガイド',
    summary_long: 'リードレプリカ、シャーディング、CQRS、マルチリージョン配置など、データベーススケーリングの主要パターンを段階的に解説。各パターンの適用条件、実装コスト、運用負荷を比較表で整理。CockroachDB、TiDB、PlanetScaleの事例も紹介。',
    tags: ['database', 'scaling', 'distributed-systems'],
    personal_score: 0.90,
    org_score: 0.60,
    novelty: 0.45,
    base_score: 0.72,
    status: 'active',
    pin: 0,
    r2_path: 'content/2025/01/i9j0k1l2m3n4.txt.gz',
    created_at: '2025-01-07T10:30:00Z',
    processed_at: '2025-01-07T10:32:00Z',
  },
  {
    id: 'j0k1l2m3n4o5',
    source: 'extension',
    url: 'https://example.com/developer-productivity-metrics',
    url_hash: 'hash010',
    title: 'Measuring Developer Productivity Without Destroying Morale',
    summary_short: '開発者生産性の計測手法とその落とし穴について考察',
    summary_long: 'DORA メトリクス、SPACE フレームワーク、DX Core 4 などの開発者生産性計測手法を比較。定量指標偏重の危険性と、定性的フィードバックとの組み合わせ方を解説。エンジニアリングマネージャー向けの実践ガイド。',
    tags: ['developer-productivity', 'engineering-management', 'metrics'],
    personal_score: 0.75,
    org_score: 0.85,
    novelty: 0.50,
    base_score: 0.72,
    status: 'archived',
    pin: 0,
    r2_path: 'content/2025/01/j0k1l2m3n4o5.txt.gz',
    created_at: '2025-01-06T14:00:00Z',
    processed_at: '2025-01-06T14:01:20Z',
  },
];
